<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Recommended</name>
   <tag></tag>
   <elementGuidId>44f379e9-072f-418f-adb6-b5b5b68b2f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles__Select-sc-109olgd-2.gnPBfy.btn-style-text.DROPDOWN_BUTTON > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='results-dropdown-sort']/div[2]/div/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4154133d-d2c8-4a1b-ae67-e0a00c02eaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recommended</value>
      <webElementGuid>0f2b3fb9-3137-4568-8fb5-b9eb8fc6a95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results-dropdown-sort&quot;)/div[@class=&quot;styles__Container-sc-109olgd-0 cVBVvq dropdown-container&quot;]/div[@class=&quot;styles__DropdownContainer-sc-109olgd-1 hVnCrU&quot;]/button[@class=&quot;styles__Select-sc-109olgd-2 gnPBfy btn-style-text DROPDOWN_BUTTON&quot;]/p[1]</value>
      <webElementGuid>0c5b42a7-60dc-4925-9411-4c3641acc56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='results-dropdown-sort']/div[2]/div/button/p</value>
      <webElementGuid>d899ffea-327e-41b4-87ed-c8e7881583d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::p[2]</value>
      <webElementGuid>c45d2f47-4c2e-44ec-83f6-3ec2bed52744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency:'])[1]/following::p[2]</value>
      <webElementGuid>0215e670-b80b-4aec-acc8-518d17958039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Includes Holiday Cruises'])[1]/preceding::p[6]</value>
      <webElementGuid>796bf5ff-a82a-4aff-a1f4-b43226146c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalina &amp; Ensenada Cruise'])[1]/preceding::p[6]</value>
      <webElementGuid>dfc4c3f7-f4d1-4978-83d1-37dd67b1f987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recommended']/parent::*</value>
      <webElementGuid>ce59402f-b058-43fd-a145-6928408db590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>1403a54e-4e3d-4c59-97c8-2c524b72d168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Recommended' or . = 'Recommended')]</value>
      <webElementGuid>b181bcc3-ea87-4e01-b9f3-661ff167d7ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
