<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Recommended</name>
   <tag></tag>
   <elementGuidId>44f379e9-072f-418f-adb6-b5b5b68b2f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles__Select-sc-109olgd-2.gnPBfy.btn-style-text.DROPDOWN_BUTTON > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='results-dropdown-sort']/div[2]/div/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>74b3abdd-a114-49d7-b6b2-2e190affd3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recommended</value>
      <webElementGuid>68eb4002-1045-4b1a-997d-63f5c8ebfc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results-dropdown-sort&quot;)/div[@class=&quot;styles__Container-sc-109olgd-0 cVBVvq dropdown-container&quot;]/div[@class=&quot;styles__DropdownContainer-sc-109olgd-1 hVnCrU&quot;]/button[@class=&quot;styles__Select-sc-109olgd-2 gnPBfy btn-style-text DROPDOWN_BUTTON&quot;]/p[1]</value>
      <webElementGuid>464c5ce5-0455-4f3b-927a-b991b79d9132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='results-dropdown-sort']/div[2]/div/button/p</value>
      <webElementGuid>68262607-9279-4628-a578-b3f7da31f347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::p[2]</value>
      <webElementGuid>3f41a0e2-a41d-4b8b-9e7f-9c5d684864c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency:'])[1]/following::p[2]</value>
      <webElementGuid>8ebcb809-2bf3-4ff5-b04f-d2dc4efb18e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Includes Holiday Cruises'])[1]/preceding::p[6]</value>
      <webElementGuid>b032a303-bb16-489b-9554-bb19b728b8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalina &amp; Ensenada Cruise'])[1]/preceding::p[6]</value>
      <webElementGuid>8c9b22f4-ef54-4821-a7e1-b1979d8b4d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recommended']/parent::*</value>
      <webElementGuid>cdb70c1f-7523-4707-aade-02ce43725d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>de8a4d7d-7cfc-45bb-9f41-89527af24463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Recommended' or . = 'Recommended')]</value>
      <webElementGuid>7a257bd5-6526-41ef-b7ef-d1562e77aaf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
