<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search Cruises</name>
   <tag></tag>
   <elementGuidId>0ad03b12-46f6-4b09-8b3f-496d20712161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rciCruiseSearchWidgetSubmitButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='rciCruiseSearchWidgetSubmitButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc6919b4-7e38-4090-87b5-e9f6db5a9de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rciCruiseSearchWidgetSubmitButton</value>
      <webElementGuid>5c2e1a1e-4a0d-48df-8545-13f6e304af13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cruise-search-widget__button cruise-search-widget__button--blue</value>
      <webElementGuid>827e7591-d9a6-408b-9b36-24afd94a77fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Cruises</value>
      <webElementGuid>09b0b925-96a7-4861-b2d4-523101822d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetSubmitButton&quot;)</value>
      <webElementGuid>f0988690-afb6-4702-a4af-11bc1383aed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='rciCruiseSearchWidgetSubmitButton']</value>
      <webElementGuid>ae7b1ff6-2a58-4102-ad7f-af7d595b8f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div[4]/button</value>
      <webElementGuid>52ecedc9-5bb0-4a16-bd7e-71b0cf9ad637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Dec ', &quot;'&quot;, '23')])[1]/following::button[1]</value>
      <webElementGuid>31c7f72a-988c-4077-bf77-be71ca30201a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaving'])[1]/following::button[1]</value>
      <webElementGuid>fc1eec63-22ee-43cd-9372-b3cf38d7852c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::button[1]</value>
      <webElementGuid>56bf7b24-760d-4429-ada3-97b0e6c9e4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/button</value>
      <webElementGuid>15a8404e-17c6-4d0e-b432-504ee6f187e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'rciCruiseSearchWidgetSubmitButton' and (text() = 'Search Cruises' or . = 'Search Cruises')]</value>
      <webElementGuid>697cead8-bf4e-4b58-9919-3ec8b9110138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
