<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Departing from Any Departure Port</name>
   <tag></tag>
   <elementGuidId>abb56e65-db5d-4938-8b30-5b86d25087e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rciCruiseSearchWidgetDeparturePortsFilter > div.cruise-search-widget__filter__holder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rciCruiseSearchWidgetDeparturePortsFilter']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d13b2ff-1347-4473-809d-c56b239d1532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cruise-search-widget__filter__holder</value>
      <webElementGuid>610ae538-4958-4177-8acb-7c525faca3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departing from Any Departure Port </value>
      <webElementGuid>dad84763-832a-4737-b61c-db90e594208c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetDeparturePortsFilter&quot;)/div[@class=&quot;cruise-search-widget__filter__holder&quot;]</value>
      <webElementGuid>5f6deef3-7e9e-4999-a172-5d57a48272b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rciCruiseSearchWidgetDeparturePortsFilter']/div</value>
      <webElementGuid>7428887e-d541-4439-a861-e2dc7727d344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/following::div[2]</value>
      <webElementGuid>ab4b4c67-59a6-4196-bfd5-074aef718350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cruising to'])[1]/following::div[3]</value>
      <webElementGuid>b001e9e9-0c3d-488f-9bc2-c50f6120b5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div</value>
      <webElementGuid>8ea77979-c1c2-4e17-9891-9d8404e243b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Departing from Any Departure Port ' or . = 'Departing from Any Departure Port ')]</value>
      <webElementGuid>3bb7a8d4-ef2f-4ac6-8995-f86a8e886f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
