<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_cruise rooms_notification-banner__secti_617cae</name>
   <tag></tag>
   <elementGuidId>ca8f36a5-aba5-451c-a03f-2f9d923a5b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.notification-banner__section-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f137023-ee5e-4556-bf74-3cb0337c90d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notification-banner__section-close</value>
      <webElementGuid>940267e2-e1df-4014-9641-33ef15c05134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container__base layout-container__base--full-width layoutContainer__base--root&quot;]/div[@class=&quot;layout-container__content&quot;]/div[@class=&quot;notification-banner__wrapper notification-banner__wrapper--visible&quot;]/div[@class=&quot;notification-banner__body&quot;]/div[@class=&quot;notification-banner__modal&quot;]/div[@class=&quot;notification-banner__section-close&quot;]</value>
      <webElementGuid>303a493b-584d-4c59-b51e-93b0b826775b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>40b39ccf-e5d1-471c-8c56-7399addcb5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>2b96b46f-b8f7-4fd4-82d5-c009d986d579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
