<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cruising to Any Destination</name>
   <tag></tag>
   <elementGuidId>4fb15b55-fffa-4b8b-bf0b-e3aa2d949169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cruise-search-widget__filter__holder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rciCruiseSearchWidgetDestinationsFilter']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e261b0f-c0bc-4a6e-86e2-60a4008e3682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cruise-search-widget__filter__holder</value>
      <webElementGuid>22e61f94-40fb-47a5-b799-7d1aa3984b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cruising to Any Destination </value>
      <webElementGuid>494d93cf-7346-4961-9286-503bea958d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetDestinationsFilter&quot;)/div[@class=&quot;cruise-search-widget__filter__holder&quot;]</value>
      <webElementGuid>e9c3ab03-b149-4c19-b25e-dbc5842b4e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rciCruiseSearchWidgetDestinationsFilter']/div</value>
      <webElementGuid>f0d9ecd8-bad9-48a7-917e-446dfb59a02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Cruise'])[2]/following::div[3]</value>
      <webElementGuid>e434ea62-055d-4ce3-8069-73163ab1bb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now'])[2]/following::div[16]</value>
      <webElementGuid>bdd6abef-1de3-4c14-bfc4-19147a9c0fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>68eed6d1-34c5-49da-83e8-8036f0880eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cruising to Any Destination ' or . = 'Cruising to Any Destination ')]</value>
      <webElementGuid>692edad0-22f1-48da-8a00-f170f7452df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
