<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Departing from Any Departure Port</name>
   <tag></tag>
   <elementGuidId>abb56e65-db5d-4938-8b30-5b86d25087e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rciCruiseSearchWidgetDeparturePortsFilter > div.cruise-search-widget__filter__holder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rciCruiseSearchWidgetDeparturePortsFilter']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>707a1d83-c0e6-46a7-b5cc-f89338f21bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cruise-search-widget__filter__holder</value>
      <webElementGuid>250c1331-e3d0-4a24-94ab-4b4271f89396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departing from Any Departure Port </value>
      <webElementGuid>5a78099a-7fb8-4749-bb30-eb3b4d8bd945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetDeparturePortsFilter&quot;)/div[@class=&quot;cruise-search-widget__filter__holder&quot;]</value>
      <webElementGuid>5042b92e-28c9-4772-a14e-171a82758f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rciCruiseSearchWidgetDeparturePortsFilter']/div</value>
      <webElementGuid>27e9c0b4-99d9-46b1-a192-80554bc697d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/following::div[2]</value>
      <webElementGuid>cdc90b82-bff7-4df7-b26e-caa22ec64938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cruising to'])[1]/following::div[3]</value>
      <webElementGuid>de226a26-a6aa-4765-a37f-ef22046cf77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div</value>
      <webElementGuid>0dd0a0d5-7400-4133-832f-1aa9b743f68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Departing from Any Departure Port ' or . = 'Departing from Any Departure Port ')]</value>
      <webElementGuid>5e330ed6-2698-4847-8ddd-f12e1e2a581d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
