<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_cruise rooms_notification-banner__secti_617cae</name>
   <tag></tag>
   <elementGuidId>ca8f36a5-aba5-451c-a03f-2f9d923a5b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.notification-banner__section-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45d7285f-8df6-4587-b6eb-58b6bf88796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notification-banner__section-close</value>
      <webElementGuid>fafbad04-3a23-40f1-942b-dc02cc425410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container__base layout-container__base--full-width layoutContainer__base--root&quot;]/div[@class=&quot;layout-container__content&quot;]/div[@class=&quot;notification-banner__wrapper notification-banner__wrapper--visible&quot;]/div[@class=&quot;notification-banner__body&quot;]/div[@class=&quot;notification-banner__modal&quot;]/div[@class=&quot;notification-banner__section-close&quot;]</value>
      <webElementGuid>37c2e45a-7670-4bb9-8b8c-58ea351f5092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>ae9ea2f5-d1e8-40a3-8992-d97db85e1b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cruise rooms'])[1]/following::div[7]</value>
      <webElementGuid>8aaf42f5-2709-4061-92a1-e5c2876c2ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='boldest cruise ships'])[1]/following::div[7]</value>
      <webElementGuid>597b45ea-9176-4dfa-b7c4-5df24e1910da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up and receive $50 OFF your next sailing!'])[1]/preceding::div[2]</value>
      <webElementGuid>ed3fdace-70ff-4199-879d-378158835e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your email address'])[1]/preceding::div[2]</value>
      <webElementGuid>40874442-55f2-4c09-af0b-5173f4dad17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>eab9e83c-a375-40cd-b2a8-dc7673b23ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
