<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Leaving Any Date</name>
   <tag></tag>
   <elementGuidId>e7287f8c-1a7c-48d0-a4c6-7b4e083c1de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rciCruiseSearchWidgetDatesFilter > div.cruise-search-widget__filter__holder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rciCruiseSearchWidgetDatesFilter']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4ee9dfe-8249-4075-8457-5fd891f869d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cruise-search-widget__filter__holder</value>
      <webElementGuid>1fea07fe-59b4-4704-883f-4d6db3f77581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leaving Any Date </value>
      <webElementGuid>4aa05d03-112a-4dfb-8ce9-9d1a1caa3db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetDatesFilter&quot;)/div[@class=&quot;cruise-search-widget__filter__holder&quot;]</value>
      <webElementGuid>b9c04eee-9ca8-4d7c-82aa-6239d1b70ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rciCruiseSearchWidgetDatesFilter']/div</value>
      <webElementGuid>7b14e4b0-314d-4aaa-9004-267666d08c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los Angeles, California'])[1]/following::div[2]</value>
      <webElementGuid>1ac6c31d-ff76-4e26-bb73-294af3e428c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departing from'])[1]/following::div[3]</value>
      <webElementGuid>60998309-133e-491b-8ec3-0f46326c69c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[3]/div</value>
      <webElementGuid>de84fca0-cb0f-471a-9190-44dbf0f25d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Leaving Any Date ' or . = 'Leaving Any Date ')]</value>
      <webElementGuid>3e3b3a0f-163e-4930-b9e7-218ac932eb58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
