<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_cruise rooms_notification-banner__secti_617cae</name>
   <tag></tag>
   <elementGuidId>ca8f36a5-aba5-451c-a03f-2f9d923a5b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.notification-banner__section-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec11c098-f136-4a31-8958-f0b9e159d691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notification-banner__section-close</value>
      <webElementGuid>9ead0e2a-73e4-42b4-b311-185343692b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-container__base layout-container__base--full-width layoutContainer__base--root&quot;]/div[@class=&quot;layout-container__content&quot;]/div[@class=&quot;notification-banner__wrapper notification-banner__wrapper--visible&quot;]/div[@class=&quot;notification-banner__body&quot;]/div[@class=&quot;notification-banner__modal&quot;]/div[@class=&quot;notification-banner__section-close&quot;]</value>
      <webElementGuid>7fe3d02c-ed49-48d4-bedf-56882b4f5aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>d6033f6e-95c2-44be-8444-afeba9996d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>a2d9c7fe-aceb-4fdd-84a9-e5d83bbb3ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
