<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search Cruises</name>
   <tag></tag>
   <elementGuidId>01d409d8-3eef-4a0e-bc11-9a712211c11c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rciCruiseSearchWidgetSubmitButton > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='rciCruiseSearchWidgetSubmitButton']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b286583-5f61-44f8-85ec-72ef59bf67b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Cruises</value>
      <webElementGuid>f7d2f4c8-e03a-48f5-bd39-1c38f2811999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetSubmitButton&quot;)/span[1]</value>
      <webElementGuid>39992dd8-674e-44b3-9ce9-0574f3e3db36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='rciCruiseSearchWidgetSubmitButton']/span</value>
      <webElementGuid>8e4f6d8f-8abe-4922-ab75-960fd75ccc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Dec ', &quot;'&quot;, '23')])[1]/following::span[3]</value>
      <webElementGuid>c25677e1-fd03-417b-8142-dcfa9d6e6af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaving'])[1]/following::span[4]</value>
      <webElementGuid>8d609e99-2f28-4253-bbcd-9bd14dfc82cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::span[2]</value>
      <webElementGuid>06159379-c80c-4e73-ac9d-a1dd53acb1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb'])[1]/preceding::span[2]</value>
      <webElementGuid>022f2a11-3303-4743-b6d0-9ce13cbaf3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>1d27ee92-5ff2-41b2-89c5-032887e8bc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search Cruises' or . = 'Search Cruises')]</value>
      <webElementGuid>5595f456-d371-46db-884b-fceb35d660de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
