<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Any Destination_cruise-search-widget___147864</name>
   <tag></tag>
   <elementGuidId>dd4d69b0-cd4f-45e6-a7ab-024445230ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cruise-search-widget__icon__caret__icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e521e7a-820f-40e1-ac97-8c67f8440f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cruise-search-widget__icon__caret__icon</value>
      <webElementGuid>578ddd09-e10d-4d2b-a30c-4b85f7216cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rciCruiseSearchWidgetDestinationsFilter&quot;)/div[@class=&quot;cruise-search-widget__filter__holder&quot;]/div[@class=&quot;cruise-search-widget__selector&quot;]/span[@class=&quot;cruise-search-widget__icon cruise-search-widget__icon__caret&quot;]/span[@class=&quot;cruise-search-widget__icon__caret__icon&quot;]</value>
      <webElementGuid>15418734-dd29-4cdf-99f9-059a03581ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rciCruiseSearchWidgetDestinationsFilter']/div/div[2]/span[2]/span</value>
      <webElementGuid>e3a0e777-9050-4b5c-b30f-0e07e2c6d2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>59b3ec7f-2409-48a7-a409-1870ed954b91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
